#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ namespaces=[
#@  'auth',
#@  'cert-manager',
#@  'istio-system',
#@  'knative-eventing',
#@  'knative-serving',
#@  'kubeflow',
#@  'kubeflow-user-example-com',
#@  ]

#@ if not data.values.Docker.use_account:
#@  namespaces.append('auth')
#@ end


#@ for i in range(len(namespaces)):
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-io-secret
  namespace: #@ namespaces[i]
data:
  .dockerconfigjson: #@ data.values.dockerconfigjson
type: kubernetes.io/dockerconfigjson
#@ end

---

#@overlay/match by=overlay.subset({"kind": "ServiceAccount", "metadata": {"name": default, "namespace": default}})
---
imagePullSecrets:
  -name: docker-io-secret

---

#@overlay/match by=overlay.subset({"kind": "Namespace"})
---
metadata:
  labels:
  #@overlay/mtach missing_ok=True
  pod-security.kubernetes.io/enforce: privileged